homebrew:
  taps:
    shared:
      - "nikitabobko/tap"
    work:
      - "azure/functions"
    private:
  brews:
    shared:
      - "macos-trash"
    work:
      - "cliclick" # macOS only - GUI automation
    private:
      - "mas" # Required for masApps installation
  casks:
    shared:
      - "visual-studio-code"
      - "alt-tab"
      - "thebrowsercompany-dia"
      - "keka"
      - "keyboardcleantool"
      - "ghostty"
      - "input-source-pro"
      # - "mactex"
      - "mockoon"
      - "notion"
      - "nikitabobko/tap/aerospace"
      - "obs"
      - "orbstack"
      - "pdf-expert"
      - "rustdesk"
      - "slack"
      - "slidepilot"
      - "tailscale-app"
      - "karabiner-elements"
    work:
      - "iterm2"
      - "obsidian"
      - "cursor"
    private:
      - "1password"
      - "adguard"
      - "balenaetcher"
      - "bob-app"
      - "chatgpt"
      - "cleanmymac"
      - "grammarly-desktop"
      - "iina" # video player
      - "logseq"
      - "notion-calendar"
      - "raycast" # (HotKey: alt/option + space)search, caculate and run scripts(with many plugins)
      - "setapp"
      - "soundsource"
      - "surge"
      - "telegram"
      - "discord"
      - "zoom"
  masApps:
    shared:
    work:
    private:
      - ["KeystrokePro", "1572206224"]
      - ["Messenger", "1480068668"]
      - ["Magnet", "441258766"]
      - ["Texifier", "458866234"]
      - ["Notability", "360593530"]
      - ["Goodnotes6", "1444383602"]
      - ["MSWord", "462054704"]
      - ["MSExcel", "462058435"]
      - ["MSPowerPoint", "462062816"]
      - ["OneDrive", "823766827"]
      - ["WeChat", "836500024"]
sysPkgs:
  - git
  - neovim
homepkgs:
  shared:
    - "(texliveFull.withPackages (ps: with ps; []))"
    - _1password-cli
    - act
    - age
    - aria2
    - asciinema
    - atuin # shell history management
    - bat
    - bat-extras.prettybat
    - bat-extras.batwatch
    - bat-extras.batpipe
    - bat-extras.batman
    - bat-extras.batgrep
    - bat-extras.batdiff
    - claude-code
    - codex
    - gemini-cli
    - certbot
    - direnv # per-directory environment variables
    - duf
    - dust
    - eza
    - fastfetch
    - fd
    - ffmpeg
    - fzf
    - gh
    - gh-dash
    - ghq
    - git-lfs
    - glow
    - hyperfine
    - jq
    - just # use Justfile to simplify nix-darwin's commands
    - lazygit
    - mise
    - navi
    - pixi # fast Python/conda package manager
    - pre-commit
    - rclone # cloud storage sync
    - onefetch
    - openssh
    - openssl
    - ouch # a CLI tool tor compressing and decompressing for various formats
    - p7zip-rar
    - uv
    - poppler
    - pueue
    - ripgrep
    - ripgrep-all
    - sd
    - skim
    - sheldon
    - sniffnet
    - starship
    - tlrc
    - tmux
    - tokei
    - tre-command
    - wget
    - yarn-berry
    - yazi
    - yq-go
    - zoxide
    - zstd
    - k9s
  work:
    - awscli2
    - aws-sam-cli
    - azure-cli
    - azure-functions-core-tools
    - google-cloud-sdk
    - llvmPackages.openmp # libomp replacement
    - mariadb
    - poetry
    - postgresql
    - redis
    - tflint
  private:
