homebrew:
  taps:
    shared:
      - "nikitabobko/tap"
    work:
      - "azure/functions"
    private:
  brews:
    shared:
      - "macos-trash"
    work:
      - "cliclick"
      - "md5sha1sum"
      - "azure-cli"
      - "azure-functions-core-tools@4"
    private:
  casks:
    shared:
      - "visual-studio-code"
      - "alt-tab"
      - "thebrowsercompany-dia"
      - "keka"
      - "keyboardcleantool"
      - "ghostty"
      - "input-source-pro"
      # - "mactex"
      - "mockoon"
      - "notion"
      - "nikitabobko/tap/aerospace"
      - "obs"
      - "orbstack"
      - "pdf-expert"
      - "rustdesk"
      - "slack"
      - "slidepilot"
      - "tailscale"
      - "karabiner-elements"
    work:
      - "obsidian"
      - "cursor"
    private:
      - "1password"
      - "1password-cli"
      - "adguard"
      - "balenaetcher"
      - "bob"
      - "chatgpt"
      - "cleanmymac"
      - "grammarly-desktop"
      - "iina" # video player
      - "logseq"
      - "notion-calendar"
      - "raycast" # (HotKey: alt/option + space)search, caculate and run scripts(with many plugins)
      - "setapp"
      - "soundsource"
      - "surge"
      - "telegram"
      - "discord"
      - "zoom"
  masApps:
    shared:
    work:
    private:
      - [ "KeystrokePro", "1572206224" ]
      - [ "Messenger", "1480068668" ]
      - [ "Magnet", "441258766" ]
      - [ "Texifier", "458866234" ]
      - [ "Notability", "360593530" ]
      - [ "Goodnotes6", "1444383602" ]
      - [ "MSWord", "462054704" ]
      - [ "MSExcel", "462058435" ]
      - [ "MSPowerPoint", "462062816" ]
      - [ "OneDrive", "823766827" ]
      - [ "WeChat", "836500024" ]
sysPkgs:
  - git
  - neovim
homepkgs:
  shared:
    - "(texliveFull.withPackages (ps: with ps; []))"
    - act
    - age
    - aria2
    - asciinema
    - bat
    - bat-extras.prettybat
    - bat-extras.batwatch
    - bat-extras.batpipe
    - bat-extras.batman
    - bat-extras.batgrep
    - bat-extras.batdiff
    - claude-code
    - certbot
    - dust
    - fastfetch
    - fd
    - ffmpeg
    - fzf
    - gh
    - ghq
    - git-lfs
    - glow
    - go
    - hyperfine
    - jq
    - just # use Justfile to simplify nix-darwin's commands
    - lazygit
    - lsd
    - navi
    - onefetch
    - openssh
    - openssl
    - ouch # a CLI tool tor compressing and decompressing for various formats
    - p7zip-rar
    - uv
    - poppler
    - pueue
    - ripgrep
    - ripgrep-all
    - sd
    - skim
    - sheldon
    - sniffnet
    - starship
    - tenv
    - tlrc
    - tmux
    - tokei
    - tre-command
    - wget
    - yarn-berry
    - yazi
    - yq-go
    - zoxide
    - zstd
    - k9s
  work:
    - google-cloud-sdk
    - aws-sam-cli
    - mariadb
    - postgresql
    - poetry
    - redis
    - tflint
    - volta
  private:
    - mas
  extra:
    - nvitop
